pipeline {
    agent any

    environment {
        // 환경 변수 설정
        DOCKERFILE_PATH = '../docker' // Dockerfile의 상대 경로
        IMAGE_NAME = 'lsb8375/testCicd'
        DOCKER_HUB_USERNAME = 'lsb8375'
        DOCKER_HUB_PASSWORD = credentials('dockerhub_id')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Gradle Build') {
            steps {
                    dir("../../app") {
                        sh './gradlew clean build -x test'
                    }
            }
        }
/* without test
        stage('Gradle Test') {
            steps {
                sh '../../app/gradlew test'
            }
        }
*/
 //login, cleaning up step
        stage('Docker Build') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:latest -f ${DOCKERFILE_PATH} .."
            }
        }

        stage('Docker Push to Docker Hub') {
            steps {
                script {
                    sh "docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}"
                    sh "docker push ${IMAGE_NAME}:latest"
                }
            }
        }
    }
}
