pipeline {
 agent any

 environment {
     // 환경 변수 설정
     IMAGE_NAME = 'lsb8375/test-cicd'
     DOCKER_HUB_USERNAME = 'lsb8375'
 }

 stages {
     stage('Checkout') {
         steps {
             checkout scm
             sh 'pwd' // 현재 디렉토리 확인
         }
     }

 stage('Gradle Build') {
     steps {
         sh 'cd /var/jenkins_home/workspace/github_jenkins/app && ./gradlew clean build -x test'
     }
 }
/* without test
     stage('Gradle Test') {
         steps {
             sh '../../app/gradlew test'
         }
     }
*/
//login, cleaning up step
stage('Docker Build') {
        steps {
            sh '''
                docker build -t ${IMAGE_NAME}:latest -f /var/jenkins_home/workspace/github_jenkins/gitops/docker/Dockerfile /var/jenkins_home/workspace/github_jenkins/app
            '''
            //-f {Dockerfile경로} {Build할 디렉토리경로}
        }
    }


     stage('Docker Push to Docker Hub') {
         steps {
             withCredentials([usernamePassword(credentialsId: 'dockerhub_id', usernameVariable: 'DOCKER_HUB_USERNAME', passwordVariable: 'DOCKER_HUB_PASSWORD')]) {
                 sh "docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}"
                 sh "docker push ${IMAGE_NAME}:latest"
             }
         }
     }
 }
}